name: hey-you
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        required: true
        default: 'Hari'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
